"""Persistence interfaces used by the OrderFlow application layer."""

from typing import Protocol
from uuid import UUID

from .domain import Customer, Order, Shipment


class CustomerRepository(Protocol):
    def add(self, customer: Customer) -> None: ...
    def get(self, customer_id: UUID) -> Customer | None: ...


class OrderRepository(Protocol):
    def add(self, order: Order) -> None: ...
    def save(self, order: Order) -> None: ...
    def get(self, order_id: UUID) -> Order | None: ...
    def list_for_customer(self, customer_id: UUID) -> list[Order]: ...


class ShipmentRepository(Protocol):
    def add(self, shipment: Shipment) -> None: ...
    def save(self, shipment: Shipment) -> None: ...
    def get(self, shipment_id: UUID) -> Shipment | None: ...
    def get_for_order(self, order_id: UUID) -> Shipment | None: ...
