"""Behavior-defining policy artifact payload; excluded from model context."""

from .core import (BASENAMES, EVIDENCE_ID, EXCLUDED_DIRS, EXTENSIONS, SECRET_PATTERNS,
                   STOPLIST, SYSTEM, POLICY_ID)
from .protocol import CONTROL_VALUES


def artifact_payload(normative_draft3, evidence_contract):
    """Only the supplied normative document may populate these text fields."""
    return {
        "policy_id": POLICY_ID, "status": "proposed-not-frozen",
        "normative_draft3": normative_draft3,
        "evidence_contract": {"identity": EVIDENCE_ID, "normative_text": evidence_contract,
                              "certification": "externally authenticated; distinct constructor/certifier; test-only forbidden officially"},
        "budgets": {"P": 4096, "K": 12288, "H": 4096, "inventory": 2048, "generation": 2048, "source_raw": 1048576},
        "parser": {"implementation": "CPython", "version": "3.11.9", "unicode": "14.0.0", "mode": "exec", "type_comments": True},
        "anchors": {"ranks": ["exact_file", "exact_directory", "filename", "module", "declaration", "lexical"],
                    "inferred_cap": 4, "strong_before_lexical": True,
                    "identifier_regex": r"[A-Za-z_][A-Za-z0-9_]*", "bare_regex": r"[A-Za-z0-9_./\\-]+",
                    "qualified_regex": r"[A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*",
                    "stoplist": sorted(STOPLIST), "minimum_component_letters": 4,
                    "protection": ["structured_existing_target", "exact_prose_path", "unambiguous_filename"],
                    "offsets": "Unicode code points; quoted inside delimiter; lexical component start",
                    "ordering": "rank, field location, UTF-8 physical path; minimum key per file"},
        "structure": {"suffixes": [".py", ".pyi"], "depth": 1, "reverse_cap": 2, "test_cap": 2,
                      "siblings": False, "cap_before_dedup": True, "backfill": False,
                      "provider_precedence": ["x/__init__.py", "x.py", "x/__init__.pyi", "x.pyi"],
                      "root_alias_schema": {"root_alias_mode": ["enabled", "disabled"], "root_alias_basename": "explicit frozen ASCII identifier or empty when disabled"},
                      "declarations": "physical owners, including shadowed providers and qualified aliases",
                      "edges": "static base/member/route-specific initializer; no import execution",
                      "fixtures": "all applicable ancestors; original-seed provenance; nomination before dedup",
                      "tests": "ordinary test/tests directory or test_*.py/*_test.py; conftest excluded",
                      "documentation": "root and nearest README.md low priority; others task-referenced"},
        "files": {"extensions": sorted(EXTENSIONS), "basenames": sorted(BASENAMES), "excluded_directories": sorted(EXCLUDED_DIRS),
                  "excluded_directory_suffix": ".egg-info", "secret_patterns": list(SECRET_PATTERNS),
                  "normalization": "one initial BOM removed, strict UTF-8, no NUL, CRLF/CR to LF",
                  "paths": "NFC Unicode14; case preserving; UTF-8 ordering; casefold collision rejection; Windows-portable components",
                  "links": "no traversal of symlink/reparse/gitlink", "acquisition": "authenticated immutable product/deny/existence receipt; no private content"},
        "K": {"outer_open": f"[CURRENT_REPOSITORY {POLICY_ID}]\n", "outer_close": "[/CURRENT_REPOSITORY]\n",
              "file": "[FILE <J(path)> bytes=<normalized_content_bytes>]\\n<content>\\n[/FILE]\\n",
              "inventory": "[FILES]\\n<J(path)>\\n...[INVENTORY_OMITTED]\\n[/FILES]\\n",
              "packing": "outer+protected reserved; bounded prefix inventory; optional whole-block skip-and-continue; closing",
              "machine_structure": "structured objects and lengths; never content-marker search"},
        "H": {"outer": ["[ADAPTATION]\n", "[/ADAPTATION]\n"], "lane": ["[LANE]\n", "[/LANE]\n"],
              "record": ["[RECORD]\n", "\n[/RECORD]\n"], "BC_owned": ["outer_open+episodic_lane<=2048", "rule_lane+outer_close<=2048"],
              "order": "descending availability, ascending body SHA-256, ascending UTF-8 key",
              "packing": "active revisions; exact-body dedup within lane; whole-record skip-and-continue; no transfer",
              "overlap": "retain K/H and cross-lane overlap; provenance only", "retrieval": "no semantic retrieval"},
        "output": {"mode": "complete replacements", "header": "=== FILE: <canonical_path> ===\\n",
                   "single": "entire completion, CRLF/CR normalization only; preserve BOM/whitespace",
                   "multiple": "all exact header-shaped lines reserved; vector must exactly match canonical targets",
                   "reference": "existing normalized target contents/new empty; conditional inter-section LF; no BOS/EOS/chat template",
                   "terminal_allowance": 1},
        "failure_taxonomy": {"phases": ["infrastructure_validation", "task_validation", "K_admission", "output_preflight", "treatment_runtime_admission"],
                             "within_phase": "ASCII reason-code order; retain detected diagnostics",
                             "after_generation": ["infrastructure_invalid", "output_capacity_failure", "output_format_failure", "evaluator_outcome"]},
        "public_task_schema": {"fields": ["instructions", "targets"], "extras": False, "targets": "nonempty canonical deduplicated UTF-8-sorted vector",
                               "serialization": "sorted compact ensure_ascii JSON; no BOM/newline; nonnegative integers; lowercase Unicode escapes"},
        "authentication_schema": {"mode": ["official", "test-only"], "profile": "frozen external verifier identity",
                                  "production": "reviewed algorithm, authorized key fingerprints, verifier code hash; no default production signer",
                                  "cutoff": "signed registry hash, T, first public release sequence, canonical P hash"},
        "profile_schema": {"controls": CONTROL_VALUES, "unsupported": "explicit; fixed neutral behavior required",
                           "runtime_argument_types": "explicit per-control integer/decimal/boolean/string/array/native/unsupported",
                           "identities": ["model", "tokenizer", "template", "generation_prompt", "system", "runtime"],
                           "capacity": "actual per-sequence; all five conditions plus full reserve; no generation fit check",
                           "common_population": "intersection before outcomes; missing infrastructure blocks finalization"},
        "system": SYSTEM, "user_serialization": "[PUBLIC_TASK]\\n+J(P)+\\n[/PUBLIC_TASK]\\n+K+H",
        "registry_schema": {"events": ["sequence", "utc", "type", "source_identity", "previous_sha256", "actor", "payload", "certificate"],
                            "records": ["key", "kind", "body", "body_sha256", "sources", "scope", "exceptions", "predecessor", "episode", "construction", "certification", "availability", "confirmation_for_rules"],
                            "kinds": ["EPISODIC", "DESCRIPTIVE", "CONFIRMED_RULE"],
                            "certified_binding": ["body_hash", "scope_hash", "exceptions_hash", "lineage_hash", "key", "kind"]},
        "invariants": ["exact K reused", "no manual overrides", "no generation reads/feedback/retry", "no padding", "no capacity transfer",
                       "candidate blindness", "context-sufficient evidence retained", "curated-state total effect; representation matching separately certified"],
    }
